name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-

      - name: NPM Install
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Get version
        id: version
        run: |
          echo "::set-output name=version::$(npm -s run env echo '$npm_package_version')"

      - name: Compress
        run: |
          gzip dist/bundle.cjs

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          preRelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/bundle.cjs.gz
          asset_name: bundle.cjs.gz
          asset_content_type: application/gzip